// Generated by gencpp from file plumbing_client_server/Addient.msg
// DO NOT EDIT!


#ifndef PLUMBING_CLIENT_SERVER_MESSAGE_ADDIENT_H
#define PLUMBING_CLIENT_SERVER_MESSAGE_ADDIENT_H

#include <ros/service_traits.h>


#include <plumbing_client_server/AddientRequest.h>
#include <plumbing_client_server/AddientResponse.h>


namespace plumbing_client_server
{

struct Addient
{

typedef AddientRequest Request;
typedef AddientResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Addient
} // namespace plumbing_client_server


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::plumbing_client_server::Addient > {
  static const char* value()
  {
    return "4781436a0c2affec8025955a6041e481";
  }

  static const char* value(const ::plumbing_client_server::Addient&) { return value(); }
};

template<>
struct DataType< ::plumbing_client_server::Addient > {
  static const char* value()
  {
    return "plumbing_client_server/Addient";
  }

  static const char* value(const ::plumbing_client_server::Addient&) { return value(); }
};


// service_traits::MD5Sum< ::plumbing_client_server::AddientRequest> should match
// service_traits::MD5Sum< ::plumbing_client_server::Addient >
template<>
struct MD5Sum< ::plumbing_client_server::AddientRequest>
{
  static const char* value()
  {
    return MD5Sum< ::plumbing_client_server::Addient >::value();
  }
  static const char* value(const ::plumbing_client_server::AddientRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::plumbing_client_server::AddientRequest> should match
// service_traits::DataType< ::plumbing_client_server::Addient >
template<>
struct DataType< ::plumbing_client_server::AddientRequest>
{
  static const char* value()
  {
    return DataType< ::plumbing_client_server::Addient >::value();
  }
  static const char* value(const ::plumbing_client_server::AddientRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::plumbing_client_server::AddientResponse> should match
// service_traits::MD5Sum< ::plumbing_client_server::Addient >
template<>
struct MD5Sum< ::plumbing_client_server::AddientResponse>
{
  static const char* value()
  {
    return MD5Sum< ::plumbing_client_server::Addient >::value();
  }
  static const char* value(const ::plumbing_client_server::AddientResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::plumbing_client_server::AddientResponse> should match
// service_traits::DataType< ::plumbing_client_server::Addient >
template<>
struct DataType< ::plumbing_client_server::AddientResponse>
{
  static const char* value()
  {
    return DataType< ::plumbing_client_server::Addient >::value();
  }
  static const char* value(const ::plumbing_client_server::AddientResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PLUMBING_CLIENT_SERVER_MESSAGE_ADDIENT_H
