// Generated by gencpp from file plumbing_client_server/AddientRequest.msg
// DO NOT EDIT!


#ifndef PLUMBING_CLIENT_SERVER_MESSAGE_ADDIENTREQUEST_H
#define PLUMBING_CLIENT_SERVER_MESSAGE_ADDIENTREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace plumbing_client_server
{
template <class ContainerAllocator>
struct AddientRequest_
{
  typedef AddientRequest_<ContainerAllocator> Type;

  AddientRequest_()
    : num1(0)
    , num2(0)  {
    }
  AddientRequest_(const ContainerAllocator& _alloc)
    : num1(0)
    , num2(0)  {
  (void)_alloc;
    }



   typedef int32_t _num1_type;
  _num1_type num1;

   typedef int32_t _num2_type;
  _num2_type num2;





  typedef boost::shared_ptr< ::plumbing_client_server::AddientRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::plumbing_client_server::AddientRequest_<ContainerAllocator> const> ConstPtr;

}; // struct AddientRequest_

typedef ::plumbing_client_server::AddientRequest_<std::allocator<void> > AddientRequest;

typedef boost::shared_ptr< ::plumbing_client_server::AddientRequest > AddientRequestPtr;
typedef boost::shared_ptr< ::plumbing_client_server::AddientRequest const> AddientRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::plumbing_client_server::AddientRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::plumbing_client_server::AddientRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::plumbing_client_server::AddientRequest_<ContainerAllocator1> & lhs, const ::plumbing_client_server::AddientRequest_<ContainerAllocator2> & rhs)
{
  return lhs.num1 == rhs.num1 &&
    lhs.num2 == rhs.num2;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::plumbing_client_server::AddientRequest_<ContainerAllocator1> & lhs, const ::plumbing_client_server::AddientRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace plumbing_client_server

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::plumbing_client_server::AddientRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::plumbing_client_server::AddientRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::plumbing_client_server::AddientRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::plumbing_client_server::AddientRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::plumbing_client_server::AddientRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::plumbing_client_server::AddientRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::plumbing_client_server::AddientRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c68f3979e1a90aac7d1c75a1096d1e60";
  }

  static const char* value(const ::plumbing_client_server::AddientRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc68f3979e1a90aacULL;
  static const uint64_t static_value2 = 0x7d1c75a1096d1e60ULL;
};

template<class ContainerAllocator>
struct DataType< ::plumbing_client_server::AddientRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "plumbing_client_server/AddientRequest";
  }

  static const char* value(const ::plumbing_client_server::AddientRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::plumbing_client_server::AddientRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 num1\n"
"int32 num2\n"
;
  }

  static const char* value(const ::plumbing_client_server::AddientRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::plumbing_client_server::AddientRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.num1);
      stream.next(m.num2);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AddientRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::plumbing_client_server::AddientRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::plumbing_client_server::AddientRequest_<ContainerAllocator>& v)
  {
    s << indent << "num1: ";
    Printer<int32_t>::stream(s, indent + "  ", v.num1);
    s << indent << "num2: ";
    Printer<int32_t>::stream(s, indent + "  ", v.num2);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PLUMBING_CLIENT_SERVER_MESSAGE_ADDIENTREQUEST_H
